### PR TITLE
Implementation of Rerank for RankVicuna

### PR DESCRIPTION
**Pull request by yilinjz**
Rerank can take either **query + docs** or **query + hits**; examples can be found in the newly added demo/ folder.

The following fields of RankVicuna are given default values:

- context_size: int = 4096,
- prompt_mode: PromptMode = PromptMode.RANK_GPT,
- device: str = "cuda",
- num_gpus: int = 1,

Removed two fields from RankLLM (top_k_candidates and dataset); RankVicuna currently does not use those two flags, and since RankVicuna inherited from RankLLM (and RankLLM does not use them either) I removed them from RankLLM as well.

### CODE REVIEW

**Comment by sahel-sh** [comment]
Rank Vicuna and Rank_LLM already have a rerank that gets a dataset, retrieves its top k candidates and then uses the provided model to rerank them. Please look at `run_rank_llm.py` to see how the current functionally works.
If you want the added functionality for reranking the provided documents, or hits, it should not replace the current functionality. But added as extra.

**Comment by ronakice** [comment]
I feel it is fine to disentangle these? Rerank should ideally only work on reranking and not entangled with retriever? We should reorganise And have say another retrieve_and_rerank method that mirrors what you have but in a different module.

**Comment by yilinjz** [comment]
@sahel-sh @ronakice Updated the PR with changes we discussed last week.

A few questions:
1. write_rerank_result() method is now moved to the new Reranker class; do we still want to include "dataset" and "top_k_candidates" as part of the output file name?
2. I wrapped the 3 cases of retrieving into one retrieve() method in the new Retriever class, do you think this way is okay?

**Comment by yilinjz** [comment]
Accidentally closed this when resolving a conflict... made another PR here https://github.com/castorini/rank_llm/pull/24

**Pull request closed without merging**
